/**
 * Generated by IBM watsonx Code Assistant for Enterprise Java Applications
 */
package com.acme.modres.mbean.reservation;

import java.util.Arrays;
import java.util.concurrent.TimeUnit;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Timeout;

import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.junit.jupiter.api.Timeout.ThreadMode.SEPARATE_THREAD;

public class WCA_DateChecker_Test_Passing {
	@Test
	@Timeout(value = 1, unit = TimeUnit.SECONDS, threadMode = SEPARATE_THREAD)
	public void testRun2_ymZN1_lzPp0() {
		ReservationList reservationList = new ReservationList(Arrays.asList(new Reservation("1/1/2023", "1/3/2023"), new Reservation("1/5/2023", "1/7/2023")));
		DateChecker dateChecker = new DateChecker(new ReservationCheckerData(reservationList));
		dateChecker.run();
		assertTrue(true);
	}
}