/**
 * Generated by IBM watsonx Code Assistant for Enterprise Java Applications
 */
package com.acme.modres.mbean.reservation;

import java.util.concurrent.TimeUnit;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Timeout;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Timeout.ThreadMode.SEPARATE_THREAD;

public class WCA_Reservation_Test_Passing {
	@Test
	@Timeout(value = 1, unit = TimeUnit.SECONDS, threadMode = SEPARATE_THREAD)
	public void testSetToDate_sxlh0() {
		Reservation res = new Reservation("1/1/2023", "1/31/2023");
		res.setToDate("1/30/2023");
		Assertions.assertEquals("1/30/2023", res.getToDate());
	}

	@Test
	@Timeout(value = 1, unit = TimeUnit.SECONDS, threadMode = SEPARATE_THREAD)
	public void getFromDateTest_MrPo0() {
		Reservation res = new Reservation("1/1/2023", "1/31/2023");
		String fromDate = res.getFromDate();
		assertEquals("1/1/2023", fromDate);
	}

	@Test
	@Timeout(value = 1, unit = TimeUnit.SECONDS, threadMode = SEPARATE_THREAD)
	public void setFromDateTest_wEPg0() {
		Reservation res = new Reservation("12/12/2022", "12/14/2022");
		res.setFromDate("12/15/2022");
		assertEquals("12/15/2022", res.getFromDate());
	}

	@Test
	@Timeout(value = 1, unit = TimeUnit.SECONDS, threadMode = SEPARATE_THREAD)
	public void testGetToDate_wGOJ0() {
		Reservation res = new Reservation("1/1/2023", "1/31/2023");
		String toDate = res.getToDate();
		assertEquals("1/31/2023", toDate);
	}
}